---
# handlers file for deploy_httpd_app
# this handler will enable httpd on boot (disabled by default)
- name: enable httpd
  service: name=httpd enabled=yes

# this handler will start httpd after installation (httpd is not started after installation)
- name: start httpd
  service: name=httpd state=started

# this handler will reload apache (after config file deployment)
- name: reload httpd
  service: name=httpd state=reloaded
